### PR TITLE
delete X messages

### PR DESCRIPTION
**Pull request by lakshyashastri**
Should solve #21

### CODE REVIEW

**Comment by Skippy404** [comment]
I shall take a look asap (just have a some assignments due today), thanks for the solution @LakshyaShastri!

**Comment by Skippy404** [comment]
Hi there apologies for only taking a look now, looks good.
I would just prefer for it to be included in the commands section. That is refactor the added code into `bot_command.py`, hence it will be invoked when we call `/del 2` for example. Once that is done ill happily merge :)

Enjoy the rest of your evening!

**Comment by LakshyaShastri** [comment]
The "commands section"  doesn't have bot commands, from what I gather it's for running shell commands and I can't just copy-paste this code there since the function isn't asynchronous either

**Comment by Skippy404** [comment]
Oh i see the confusion, no the commands section is for invoking commands through discord, using the command prefix.
At line 134 in `__main__.py`, as that is where the commands get parsed.

Thanks!

**Comment by LakshyaShastri** [comment]
@Skippy404 Have a look now!

**Comment by Skippy404** [comment]
Yo @LakshyaShastri! I took a look, and there is just a small bug (line 130, `__main__.py`),

provided in the screenshot below is the fix, apply it and ill merge \:D
image

Enjoy the rest of your evening, and thanks!

**Comment by LakshyaShastri** [comment]
@Skippy404 No problem, did that!

**Comment by skiqqy** [comment]
Thanls @LakshyaShastri \:D

**Pull request merged**
